### ISSUE TITLE
平移

### ISSUE THREAD

**Issue by zhongcaiwei** [maptalks/maptalks.d3.js#4]
https://maptalks.github.io/maptalks.d3/demo/coastal.html
示例中，有以下几个问题：
1、缩放后，d3层消失；
2、平移操作，d3层移动，底部瓦片层没反应；
3、倾斜、旋转操作，底图切斜，d3层没反应；
![image](https://user-images.githubusercontent.com/30993872/30363941-b4846b0e-9894-11e7-802d-0539536f8ccf.png)

**Comment by fuzhenn** [comment]
已经解决, d3中使用了已弃用的方法导致
